### ISSUE TITLE
Missing URL

### ISSUE THREAD

**Issue by darogan** [broadinstitute/BipolarCell2016#1]
The url for the bipolar_data_Cell2016.Rdata data file is missing from the README file

**Comment by karthikshekhar** [comment]
Apologies! The paper was published a week earlier than we expected, but the data is now public. We could not place the .Rdata file on the github page because of its size (>100 MB), but you can download it from this link - http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE81904. 

Please note that the GEO accession number has been added to the name of the .Rdata file, which needs to be removed to be consistent with the tutorial. Thank you!
